In [1]:
from PIL import Image
import func
import jpegCompressor
import numpy as np
import matplotlib.pyplot as plt

In [25]:
im = Image.open('./data/Lenna_GS.png')
block = np.array(im)[50:100, 50:100]
block

array([[164, 161, 161, ..., 100, 103, 103],
       [165, 164, 162, ..., 110, 103, 103],
       [161, 162, 164, ..., 108, 102, 104],
       ...,
       [168, 163, 159, ..., 100, 100, 105],
       [164, 159, 159, ..., 103, 105,  99],
       [162, 159, 159, ..., 100, 101,  97]], shape=(50, 50), dtype=uint8)

In [26]:
block = Image.fromarray(block)
block = block.convert('RGB')
block = np.array(block)

In [22]:
y, Cb, Cr = func.RGB_to_YCbCr(block)

In [27]:
y

array([[164, 161, 161, ..., 100, 103, 103],
       [165, 164, 162, ..., 110, 103, 103],
       [161, 162, 164, ..., 108, 102, 104],
       ...,
       [168, 163, 159, ..., 100, 100, 105],
       [164, 159, 159, ..., 103, 105,  99],
       [162, 159, 159, ..., 100, 101,  97]], shape=(50, 50), dtype=uint8)

In [23]:
Cb


array([[128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       ...,
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128]], shape=(50, 50), dtype=uint8)

In [24]:
Cr

array([[128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       ...,
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128],
       [128, 128, 128, ..., 128, 128, 128]], shape=(50, 50), dtype=uint8)